# Generated by Django 5.1.7 on 2025-04-02 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_rename_total_amount_order_total_price_order_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="prescription",
            field=models.ImageField(blank=True, null=True, upload_to="prescriptions/"),
        ),
    ]
