# Generated by Django 5.1.7 on 2025-04-03 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_order_prescription"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="medicine",
            name="categories",
            field=models.ManyToManyField(blank=True, to="store.category"),
        ),
    ]
