# Generated by Django 5.1.7 on 2025-04-03 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0005_category_medicine_categories"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medicine",
            name="categories",
            field=models.ManyToManyField(
                blank=True, related_name="medicines", to="store.category"
            ),
        ),
    ]
